#!/bin/zsh

# Quality of life fixes
alias dir="ls"
alias docker=podman
alias td="cd \$(mktemp -d)"
alias grep=rg  # Requires ripgrep

# Env vars
export HISTFILE=~/.histfile
export HISTSIZE=5000
export HISTCONTROL=ignoredups
export HISTIGNORE="&:history:ls*:w:exit:clear:[fb]g"
export HIST_STAMPS="dd.mm.yyyy"
export SAVEHIST=1000
export EDITOR="vim"

# Attach to development tmux instance, or start it if it doesn't exist.
function ws() {
  if [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; then
    echo "You are already in your workspace."
  else
    if tmux ls | grep workspace ; then
      tmux attach -t workspace
    else
      unset ans
      while [[ ! "$ans" =~ (([yY](es|ES)?)|([nN](o|O)?)) ]]; do
        echo -n "Workspace not detected. Would you like to start it? (y/n) "
        read -r ans
      done
      if [[ "$ans" =~ [yY](es|ES)? ]]; then
        tmux new -s workspace
      fi
    fi
  fi
}

function bak() {
  cp "${1}" ".${1}.bak"
}

# Quick switch to repo from wherever on disk
function repo() {
  cd "${HOME}/Repositories/${1}" || return
}

function _repo_autocomplete() {
  reply=( $(ls ~/Repositories) )
}

compctl -K _repo_autocomplete repo

function ve() {
  if [[ -e ./.venv/bin/activate ]]; then
      . ./.venv/bin/activate
  else
      python -m venv .venv && . ./.venv/bin/activate
  fi
}

