#!/bin/zsh

if [[ $(which fdfind) ]]; then
    alias find=fdfind
    alias fd=fdfind
fi

# Wayland
if [[ ! -d $XDG_RUNTIME_DIR ]]; then
    export XDG_RUNTIME_DIR="/run/user/$(id -u)/sway"
    mkdir -p ${XDG_RUNTIME_DIR}
    chmod 700 ${XDG_RUNTIME_DIR}
fi

if [[ ! -d $GDK_BACKEND ]]; then
    export GDK_BACKEND=wayland
fi
